apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-camunda-deployment
  labels:
    app: k8-camunda
spec:
  selector:
    matchLabels:
      app: k8-camunda
  replicas: 1
  template: 
    metadata:
      labels:
        app: k8-camunda
    spec:
      containers:
      - name: bpm
        image: camunda/camunda-bpm-platform
        ports:
        - containerPort: 8080
        # specify environment variables (from cloud)